services:

  db:
    image: mariadb:10.2
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "12306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: djambred
      MYSQL_DATABASE: metabase
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: 123
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_db_metabase
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:3000"
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: 123
      MB_DB_HOST: db
    restart: unless-stopped